library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('documents/', views.DocumentListView.as_view(), name='documents'),
    path('documents/search/', views.search_documents, name='search_documents'),
    path('my_documents/<int:pk>/', views.my_documents, name='my_documents'),
    path('document/<int:pk>/', views.DocumentDetailView.as_view(), name='document-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('add_book/', views.add_book, name='add_book'),
    path('add_audio/', views.add_audio, name='add_audio'),
    path('add_video/', views.add_video, name='add_video'),
    path('add_copies/<int:pk>/', views.add_copies, name='add_copies'),
    path('remove_copies/<int:pk>/', views.remove_copies, name='remove_copies'),
    path('document/<int:doc_id>/give/<int:user_id>', views.give_document, name='give_document'),
    path('document/<int:doc_id>/increase_user_priority/<int:user_id>', views.increase_user_priority, name='increase_user_priority'),
    path('document/<int:doc_id>/reset_user_priority/<int:user_id>', views.reset_user_priority, name='reset_user_priority'),
    path('document/<int:doc_id>/reserve/', views.reserve, name='reserve'),
    path('document/<int:doc_id>/get_in_queue/', views.get_in_queue, name='get_in_queue'),
    path('document/<int:doc_id>/quit_queue/', views.quit_queue, name='quit_queue'),
    path('document/<int:doc_id>/renew/', views.renew_document, name='renew_document'),
    path('document/<int:pk>/take/<int:user_id>', views.take_document, name='take'),
    path('document/<int:pk>/delete_copy/<int:user_id>', views.delete_copy, name='delete_copy'),
    path('document/<int:pk>/delete/', views.delete_document, name='delete'),
    path('document/<int:pk>/editdocument/', views.edit_document, name='editdocument'),
    path('document/<int:doc_id>/document_outstanding_request/', views.document_outstanding_request, name='document_outstanding_request'),
    path('document/<int:doc_id>/document_disable_outstanding_request/', views.document_disable_outstanding_request, name='document_disable_outstanding_request'),
    path('add_article/', views.add_article, name='add_article'),
    path('document/<int:pk>/ask/<int:user_id>', views.ask_for_return, name='ask'),
]

login/urls.py
from django.urls import path
from login import views as login_views
from . import views
from library import urls

urlpatterns = [
    path('login/', login_views.login, name='login'),
    path('add_user/', views.add_user, name='add_user'),
    path('users/', views.CustomUserListView.as_view(), name='users'),
    path('users/<int:pk>/', views.CustomUserDetailView.as_view(), name='customuser_detail'),
    path('users/<int:pk>/deleteuser/', views.delete_user, name='deleteuser'),
    path('users/<int:pk>/edituser/', views.edit_user, name='edituser'),
    path('logout/', login_views.logout, name='logout'),
    # path('register/', login_views.register, name='register')
]

library/models/record.py
from .documents import *
from login.models import CustomUser

import uuid
import datetime

PENALTY = 100


def get_object_of_class(pk):
    """
    Recognize type of model inherited from Document by primary key.
    :param pk: id.
    :return: instance of model, inherited from Document.
    """
    doc = None

    if Book.objects.all().filter(id=pk).count() != 0:
        doc = Book.objects.get(id=pk)
    elif Article.objects.all().filter(id=pk).count() != 0:
        doc = Article.objects.get(id=pk)
    elif Audio.objects.all().filter(id=pk).count() != 0:
        doc = Audio.objects.get(id=pk)
    elif Video.objects.all().filter(id=pk).count() != 0:
        doc = Video.objects.get(id=pk)

    return doc


class Record(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this book for the whole lib')
    document = models.ForeignKey(Document, on_delete=models.SET_NULL, null=True)
    due_to = models.DateField(null=True, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    renewals_left = models.IntegerField(default=1)

    creator_email = models.CharField(max_length=50, null=True, blank=True, default="root@root.com")


    # TODO: make enum
    LOAN_STATUS = (
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='a', help_text='Document availability')

    class Meta:
        ordering = ["due_to"]
        # TODO: define permissions
        permissions = ()

    def make_available(self):
        self.due_to = None
        self.user = None
        self.status = 'a'
        self.renewals_left = 1
        self.save()

    def renew_by_user(self, user, date=None):
        """
        Recalculate due_to for user, update counter of renewals
        :param user: user, that wants to renew document
        """
        if date is None:
            date = datetime.date.today()
        if self.renewals_left > 0 and not self.document.outstanding:
            if user.subtype != 'Visiting Professors':
                self.renewals_left -= 1
            self.due_to = date + self.get_due_delta()
            self.save()

    def get_overdue(self, date=datetime.date.today()):
        return (date - self.due_to).days

    def get_overdue_fine(self, today=datetime.date.today()):
        days = self.get_overdue(today)
        if days > 0:
            if days * PENALTY <= self.document.price:
                return days * PENALTY
            else:
                return self.document.price
        else:
            return 0

    def get_due_delta(self):
        """
        Counts for how many weeks document can be taken
        """
        real_type = get_object_of_class(self.document.id)
        if 'Visiting Professors' in [x.name for x in self.user.groups.all()]:
            delta = 1
        elif isinstance(real_type, Book):
            if 'Faculty' in [x.name for x in self.user.groups.all()]:
                delta = 4
            elif real_type.is_bestseller:
                delta = 2
            else:
                delta = 3
        else:
            delta = 2

        return datetime.timedelta(weeks=delta)

library/models/request_queue.py
from django.db import models
from library.models import *
from login.models import CustomUser


class RequestQueueElement(models.Model):
    """
    Every object of this class is an element of the queue for the particular document.
    Object contains date, priority, link on user and document.
    """
    date = models.DateField()
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    document = models.ForeignKey(Document, on_delete=models.SET_NULL, null=True)
    priority = models.IntegerField(default=0)

    creator_email = models.CharField(max_length=50, null=True, blank=True, default="root@root.com")

    def default_priority(self):
        """
        Method calculates default priority depending on user type.
        :return:
        """
        if self.user.subtype == 'Students':
            return 4
        elif self.user.subtype == 'Instructors':
            return 3
        elif self.user.subtype == 'TAs':
            return 2
        elif self.user.subtype == 'Visiting Professors':
            return 1
        elif self.user.subtype == 'Professors':
            return 0

    class Meta:
        ordering = ['-priority', 'date']

    def __str__(self):
        return self.user.get_full_name()

library/models/tag.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)
    creator_email = models.CharField(max_length=50, null=True, blank=True, default="root@root.com")

    def __str__(self):
        return self.name

library/views.py
import datetime

from django.contrib.auth.decorators import permission_required
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic

from login.forms import *
from .forms import *


def index(request):
    """
    View function for home page of site.
    """

    num_docs = Document.objects.all().count()
    num_instances = Record.objects.all().count()  # number of copies of this document
    num_instances_available = Record.objects.filter(
        status='a').count()  # number of available copies of this document
    num_authors = Author.objects.count()  # number of authors

    return render(
        request,
        'index.html',
        context={'num_docs': num_docs, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available,
                 'num_authors': num_authors},
    )


class DocumentListView(generic.ListView):
    """
    Generic class-based view listing all documents in the system.
    """
    model = Document
    paginate_by = 20


class AuthorListView(generic.ListView):
    """
    Generic class-based view listing all authors in the system.
    """
    model = Author
    paginate_by = 20


class DocumentDetailView(generic.DetailView):
    """
    Generic class-based view the particular document page.
    """
    model = Document


def search_by_word(field, text):
    """
    Helper function for search_by_field
    Takes all documents which contains 'text' in the 'field'
    :param field: field for search: 'title', 'authors' or 'tags'
    :param text: string to search
    :return: set of all found documents
    """
    result = set()
    for doc in Document.objects.all():
        compare_with = ''
        if field == 'title':
            compare_with = doc.title
        elif field == 'authors':
            compare_with = doc.display_authors()
        elif field == 'tags':
            compare_with = doc.display_tags()

        if text in compare_with.lower():
            result.add(doc)

    return result


def search_by_field(field, text):
    """
    Helper function for search_documents
    Parse 'text' by substrings, work with operands and takes all documents wich contains 'text' in the 'field'
    :param field: field for search: 'title', 'authors' or 'tags'
    :param text: string to search
    :return: set of all found documents
    """
    if len(text) == 0:
        return set(Document.objects.all())
    operands = []
    unit = ''  # substring between two operands
    results_by_unit = []  # list of sets with documents
    for word in text.split():
        if word == 'OR' or word == 'AND':
            operands.append(word)
            results_by_unit.append(search_by_word(field, unit[:-1]))
            unit = ''
            continue
        unit += word.lower() + ' '

    results_by_unit.append(search_by_word(field, unit[:-1]))

    to_union = []
    current = set(Document.objects.all())
    for i in range(len(results_by_unit)):
        current = current.intersection(results_by_unit[i])
        if i < len(operands) and operands[i] == 'OR':
            to_union.append(current)
            current = set(Document.objects.all())

    to_union.append(current)

    result = set()
    for subresult in to_union:
        result = result.union(subresult)

    return result


def search_documents(request):
    """
    Advanced search by all documents
    :param request: HTTP request
    :return: rendered page with list of found documents (stored in search_results)
    """
    if request.method == 'POST':
        search_form = SearchFrom(request.POST)

        if search_form.is_valid():
            # results by every field are stored in sets
            taken = set()
            available = set()
            title = set()
            authors = set()
            tags = set()

            for doc in Document.objects.all():
                if search_form.cleaned_data['taken'] is False or doc.record_set.filter(status='o').count() != 0:
                    taken.add(doc)

                if search_form.cleaned_data['available'] is False or doc.record_set.filter(status='a').count() != 0:
                    available.add(doc)

                title = search_by_field('title', search_form.cleaned_data['title'])
                authors = search_by_field('authors', search_form.cleaned_data['authors'])
                tags = search_by_field('tags', search_form.cleaned_data['tags'])

            # intersection of results by every field
            search_results = list(
                taken.intersection(available.intersection(title.intersection(authors.intersection(tags)))))
            return render(request, 'library/advanced_search.html',
                          {'search_results': search_results, 'form': search_form})
    else:
        search_form = SearchFrom()

    return render(request, 'library/advanced_search.html',
                  {'search_results': Document.objects.all(), 'form': search_form})


def my_documents(request, pk):
    """
    View for listing document of user with given id.
    :param request: HTTP request.
    :param pk: user id.
    :return: rendered page with list of user's documents.
    """
    return render(request, 'library/my_documents_list.html', {'user': CustomUser.objects.get(id=pk)})


@permission_required('library.add_document')
def add_book(request):
    """
    View function for adding a book.
    :param request:
    :return:
    """
    if request.method == 'POST':
        author_form = AuthorForm(request.POST)
        book_form = BookForm(request.POST)
        tag_form = TagForm(request.POST)

        if tag_form.is_valid():
            tag = tag_form.save(commit=True)
            tag.creator_email = request.user.email
            tag.save()
            return HttpResponseRedirect(reverse('add_book'))

        if author_form.is_valid():
            author = author_form.save(commit=True)
            author.creator_email = request.user.email
            author.save()
            return HttpResponseRedirect(reverse('add_book'))

        if book_form.is_valid():
            document = book_form.save(commit=True)
            document.creator_email = request.user.email
            document.save()
            for _ in range(book_form.cleaned_data['num_of_copies']):
                rec = Record.objects.create(document=document)
                rec.creator_email = request.user.email
                rec.save()
            return HttpResponseRedirect('../')
    else:
        author_form = AuthorForm()
        book_form = BookForm()
        tag_form = TagForm()

    return render(request, 'add_book.html', {'book_form': book_form, 'author_form': author_form, 'tag_form': tag_form})


@permission_required('library.add_document')
def add_article(request):
    """
    Add article view.
    :param request: HTTP request.
    :return: HTTP redirect.
    """
    if request.method == 'POST':
        author_form = AuthorForm(request.POST)
        article_form = ArticleForm(request.POST)
        tag_form = TagForm(request.POST)

        if tag_form.is_valid():
            tag = tag_form.save(commit=True)
            tag.creator_email = request.user.email
            tag.save()
            return HttpResponseRedirect(reverse('add_article'))

        if author_form.is_valid():
            author = author_form.save(commit=True)
            author.creator_email = request.user.email
            author.save()
            return HttpResponseRedirect(reverse('add_article'))

        if article_form.is_valid():
            document = article_form.save(commit=True)
            document.creator_email = request.user.email
            document.save()
            for _ in range(article_form.cleaned_data['num_of_copies']):
                rec = Record.objects.create(document=document)
                rec.creator_email = request.user.email
                rec.save()
            return HttpResponseRedirect('../')
    else:
        author_form = AuthorForm()
        article_form = ArticleForm()
        tag_form = TagForm()

    return render(request, 'add_article.html',
                  {'article_form': article_form, 'author_form': author_form, 'tag_form': tag_form})


@permission_required('library.add_document')
def add_audio(request):
    """
    Add audio view.
    :param request: HTTP request.
    :return: HTTP redirect.
    """
    if request.method == 'POST':
        author_form = AuthorForm(request.POST)
        audio_form = AudioForm(request.POST)
        tag_form = TagForm(request.POST)

        if tag_form.is_valid():
            tag = tag_form.save(commit=True)
            tag.creator_email = request.user.email
            tag.save()
            return HttpResponseRedirect(reverse('add_audio'))

        if author_form.is_valid():
            author = author_form.save(commit=True)
            author.creator_email = request.user.email
            author.save()
            return HttpResponseRedirect(reverse('add_audio'))

        if audio_form.is_valid():
            document = audio_form.save(commit=True)
            document.creator_email = request.user.email
            document.save()
            for _ in range(audio_form.cleaned_data['num_of_copies']):
                rec = Record.objects.create(document=document)
                rec.creator_email = request.user.email
                rec.save()
            return HttpResponseRedirect('../')
    else:
        author_form = AuthorForm()
        audio_form = AudioForm()
        tag_form = TagForm()

    return render(request, 'add_audio.html',

library/templates/library/advanced_search.html
{% extends "base_generic.html" %}

{% block content %}


    <h1 style="color: rgba(123,123,112,0.55) ">Advanced Search</h1>


     <form method="POST" action="{% url 'search_documents' %}">
        {% csrf_token %}

        <p align="right">
            <label class="radio-inline"><input type="checkbox" name="available" {% if form.cleaned_data.available %} checked {%endif%}"/> Available </label>
            <label class="radio-inline"><input type="checkbox" name="taken" {% if form.cleaned_data.taken %} checked {%endif%}/> Taken </label>
            &nbsp;&nbsp;
            <i class="fa fa-search fa-fw"><input class="btn btn-search" type="submit" value="Search"/></i>
        </p>

        <div class="col-md-*">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th><input class="form-control" type="text" placeholder="Title" name="title" value="{{form.cleaned_data.title}}"></th>
                    <th><input class="form-control" type="text" placeholder="Authors" name="authors" value="{{form.cleaned_data.authors}}"></th>
                    <th><input class="form-control" type="text" placeholder="Tags" name="tags" value="{{form.cleaned_data.tags}}"></th>
                </tr>
                </thead>
                <tbody id="DocumentList">
                {% for doc in search_results %}
                    <tr>
                        <td><a href="{{ doc.get_absolute_url }}">{{ doc.title }}</a></td>
                        <td>
                            {{ doc.display_authors }}
                        </td>
                        <td>
                            {{ doc.display_tags }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
     </form>

    <style>

        .btn-search {
            background: #747edb;
            border-radius: 7px;
            color: #fff;
            border-width: 1px;
            border-style: solid;
            border-color: #747edb;
        }

        .btn-search:link, .btn-search:visited {
            color: #fff;
        }

        .btn-search:active, .btn-search:hover {
            background: #1c1c1c;
            color: #fff;
        }


    </style>


{% endblock %}

library/templates/library/author_list.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Author List</h1>

    {% if author_list %}
    <div class="col-md-*">
            <input class="form-control" id="myInput" type="text" placeholder="Search..">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Period of life</th>
                </tr>
                </thead>
                <tbody id="AuthorList">
                    {% for author in author_list %}
                        <tr>
                            <td><a href="">{{ author.first_name }}</a></td>
                            <td><a href="">{{ author.last_name }}</a></td>
                            <td>{{ author.date_of_birth }} - {{ author.date_of_death }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
      <p>There are no authors in library.</p>
    {% endif %}

{% endblock %}

library/templates/library/document_list.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Document List</h1>
    <p align="right"><a class = "btn btn-warning" href="{% url 'search_documents' %}">Advanced search</a></p>

    {% if document_list %}
        <div class="col-md-*">
            <input class="form-control" id="DocumentListInp" type="text" placeholder="Search..">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Authors</th>
                </tr>
                </thead>
                <tbody id="DocumentList">
                {% for doc in document_list %}
                    <tr>
                    <td><a href = "{{ doc.get_absolute_url }}">{{ doc.title }}</a></td>
                    <td>
                        {{doc.display_authors}}
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
      <p>There are no documents in the library.</p>
    {% endif %}

    {% if user.is_authenticated and perms.library.can_change %}
        <div class="alert alert-info">
            <h3> Checked out documents </h3>
            <div class="col-md-*">
                <input class="form-control" id="CheckedOutDocumentsListInp" type="text" placeholder="Search..">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Authors</th>
                        <th>User</th>
                        <th>Due to</th>
                        <th>Fee</th>
                    </tr>
                    </thead>
                    <tbody id="CheckedOutDocumentsList">
                    {% for document in document_list %}
                        {% for rec in document.record_set.all %}
                            {% if rec.status == 'o' %}
                                {% if rec.get_overdue_fine > 0 %}
                                    <tr class="danger">
                                    <td style="display:none">overdue debtor</td>
                                {% else %}
                                    <tr>
                                {% endif %}
                                <td><a href = "{{ rec.document.get_absolute_url }}">{{ rec.document.title }}</a></td>
                                <td>
                                    {{rec.document.display_authors}}
                                </td>
                                <td><a href="{{rec.user.get_absolute_url}}">{{rec.user}}</a></td>
                                <td>{{rec.due_to}}</td>
                                <td>{{rec.get_overdue_fine}} RUB</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            To show all debtors search for "debtor" or "overdue"
        </div>
    {% endif %}


{% endblock %}


library/templates/library/edit_document.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Edit document</h1>

    <form method="POST" autocomplete="on">
    {% csrf_token %}
        {{ form | crispy }}
        <input class="btn btn-primary" type="submit" value="Save"/>
    <br>
    <br>
    </form>
{% endblock %}

library/templates/library/my_documents_list.html
{% extends "base_generic.html" %}
{% load login_extras %}

{% block content %}

    <h1>My documents</h1>

    <div class="col-md-*">
        <div class="alert alert-success">
            <h3>Checked out books</h3>
            {% if user|taken_books_list %}

                <input class="form-control" id="TakenDocs" type="text" placeholder="Search..">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Authors</th>
                        <th>Due to</th>
                        <th>Fee</th>
                    </tr>
                    </thead>
                    <tbody id="DocumentTakenList">
                    {% for rec in user|taken_books_list %}
                        {% if user|overdue_document:rec.document %}
                            <tr class="danger">
                                <td style="display:none">overdue</td>
                        {% else %}
                            <tr>
                        {% endif %}
                            <td><a href="{{ rec.document.get_absolute_url }}">{{ rec.document.title }}</a></td>
                            <td>
                                {{ rec.document.display_authors }}
                            </td>
                            <td>{{ rec.due_to }}</td>
                            <td>{{rec.get_overdue_fine}} RUB</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                To show all overdue documents search for "overdue"
            {% else %}
                <p>You have not taken any document</p>
            {% endif %}
        </div>
        <div class="alert alert-info">
            <h3>Reserved books</h3>
            {% if user|reserved_books_list %}
                <input class="form-control" id="ReservedDocs" type="text" placeholder="Search..">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Authors</th>
                    </tr>
                    </thead>
                    <tbody id="DocumentReservedList">
                    {% for rec in user|reserved_books_list %}
                        <tr>
                            <td><a href="{{ rec.document.get_absolute_url }}">{{ rec.document.title }}</a></td>
                            <td>
                                {{rec.document.display_authors}}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h5>You have no any reserved documents</h5>
            {% endif %}
        </div>
    </div>



     {% if user.requestqueueelement_set.all %}
        <div class="col-md-*">
            <div class="alert alert-success">
            <h3>My lines</h3>
                <input class="form-control" id="TakenDocs" type="text" placeholder="Search..">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Authors</th>
                    </tr>
                    </thead>
                    <tbody id="DocumentTakenList">
                    {% for queue_element in user.requestqueueelement_set.all %}
                            <tr>
                            <td><a href="{{ queue_element.document.get_absolute_url }}">{{ queue_element.document.title }}</a></td>
                            <td>
                                {{queue_element.document.display_authors}}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}





{% endblock %}