login/urls.py
from django.urls import path
from login import views as login_views
from . import views
from library import urls

urlpatterns = [
    path('login/', login_views.login, name='login'),
    path('add_user/', views.add_user, name='add_user'),
    path('users/', views.CustomUserListView.as_view(), name='users'),
    path('users/<int:pk>/', views.CustomUserDetailView.as_view(), name='customuser_detail'),
    path('users/<int:pk>/deleteuser/', views.delete_user, name='deleteuser'),
    path('users/<int:pk>/edituser/', views.edit_user, name='edituser'),
    path('logout/', login_views.logout, name='logout'),
    # path('register/', login_views.register, name='register')
]

library/models/record.py
from .documents import *
from login.models import CustomUser

import uuid
import datetime

PENALTY = 100


def get_object_of_class(pk):
    """
    Recognize type of model inherited from Document by primary key.
    :param pk: id.
    :return: instance of model, inherited from Document.
    """
    doc = None

    if Book.objects.all().filter(id=pk).count() != 0:
        doc = Book.objects.get(id=pk)
    elif Article.objects.all().filter(id=pk).count() != 0:
        doc = Article.objects.get(id=pk)
    elif Audio.objects.all().filter(id=pk).count() != 0:
        doc = Audio.objects.get(id=pk)
    elif Video.objects.all().filter(id=pk).count() != 0:
        doc = Video.objects.get(id=pk)

    return doc


class Record(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this book for the whole lib')
    document = models.ForeignKey(Document, on_delete=models.SET_NULL, null=True)
    due_to = models.DateField(null=True, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    renewals_left = models.IntegerField(default=1)

    creator_email = models.CharField(max_length=50, null=True, blank=True, default="root@root.com")


    # TODO: make enum
    LOAN_STATUS = (
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='a', help_text='Document availability')

    class Meta:
        ordering = ["due_to"]
        # TODO: define permissions
        permissions = ()

    def make_available(self):
        self.due_to = None
        self.user = None
        self.status = 'a'
        self.renewals_left = 1
        self.save()

    def renew_by_user(self, user, date=None):
        """
        Recalculate due_to for user, update counter of renewals
        :param user: user, that wants to renew document
        """
        if date is None:
            date = datetime.date.today()
        if self.renewals_left > 0 and not self.document.outstanding:
            if user.subtype != 'Visiting Professors':
                self.renewals_left -= 1
            self.due_to = date + self.get_due_delta()
            self.save()

    def get_overdue(self, date=datetime.date.today()):
        return (date - self.due_to).days

    def get_overdue_fine(self, today=datetime.date.today()):
        days = self.get_overdue(today)
        if days > 0:
            if days * PENALTY <= self.document.price:
                return days * PENALTY
            else:
                return self.document.price
        else:
            return 0

    def get_due_delta(self):
        """
        Counts for how many weeks document can be taken
        """
        real_type = get_object_of_class(self.document.id)
        if 'Visiting Professors' in [x.name for x in self.user.groups.all()]:
            delta = 1
        elif isinstance(real_type, Book):
            if 'Faculty' in [x.name for x in self.user.groups.all()]:
                delta = 4
            elif real_type.is_bestseller:
                delta = 2
            else:
                delta = 3
        else:
            delta = 2

        return datetime.timedelta(weeks=delta)

login/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.urls import reverse
from django.contrib.auth.models import PermissionsMixin
from django.core.exceptions import ValidationError


class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, phone_number, address, password=None):
        """
        Creates and saves a CustomUser with the given email, password,
        first name and last name.
        :param email:
        :param password:
        :param first_name:
        :param last_name:
        :param phone_number
        :param address
        :return:
        """
        if not email:
            raise ValueError('User must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            address=address
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, phone_number, address, password):
        """
        Creates and saves a superuser with the
        :param address:
        :param phone_number:
        :param last_name:
        :param first_name:
        :param email:
        :param password:
        :return:
        """
        if len(CustomUser.objects.filter(is_admin=True)) + 1 > 1:
            raise ValidationError("Can only create 1 instance of Admin")

        user = self.create_user(email,
                                first_name=first_name,
                                last_name=last_name,
                                phone_number=phone_number,
                                address=address,
                                password=password,
                                )
        user.is_admin = True
        user.save(using=self._db)
        return user

    def get_by_natural_key(self, email):
        return self.get(email=email)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    address = models.TextField(max_length=500)
    subtype = models.CharField(max_length=20, null=True, blank=True)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone_number', 'address']

    objects = CustomUserManager()

    creator_email = models.CharField(max_length=50, null=True, blank=True, default="")

    def delete_user(self): # TODO Move it to user manager
        """
        Delete current user
        """
        self.delete()

    def get_absolute_url(self):
        """
        :return: the url to access a particular Document instance.
        """
        return reverse('customuser_detail', args=[str(self.id)])

    def get_full_name(self):
        """
        The user is identified by their email address
        :return: user email address
        """
        return self.email

    def get_short_name(self):
        """
        The user is identified by their email address
        :return: user email address
        """
        return self.email

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        """
        Does the user have a specific permission?
        :param perm: permission
        :param obj:
        """
        if self.is_admin or perm in self.get_all_permissions():
            return True
        return False

    # TODO: implement method
    def has_module_perms(self, app_label):
        """
        Does the user have permissions to view the app 'app_label'?
        :param app_label: application
        """
        return True

    @property
    def is_staff(self):
        """
        Is the user a member of staff?
        """
        return self.is_admin




login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.views import generic
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .forms import *
from django.contrib.auth.models import Group


class CustomUserListView(generic.ListView):
    """
    Generic class-based view listing all users in the system.
    """
    model = CustomUser


class CustomUserDetailView(generic.DetailView):
    """
    Generic class-based view the particular user.
    """
    model = CustomUser

@permission_required('login.delete_customuser')
def delete_user(request, pk):
    """
    Delete user from the system.
    :param request: HTTP request.
    :param pk: user id.
    :return: HTTP redirect to user page.
    """
    user = CustomUser.objects.get(pk=pk)
    user.delete_user()
    return HttpResponseRedirect(reverse('users'))


def get_or_create_group(name):
    if Group.objects.filter(name=name).count() != 0:
        return Group.objects.get(name=name)
    group = Group.objects.create(name=name)
    return group


@permission_required('login.change_customuser')
def edit_user(request, pk):
    """
    View function for editing a user.
    :param request: HTTP request.
    :param pk: user id.
    :return: rendered edit_user page.
    """
    user = CustomUser.objects.get(pk=pk)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user, caller_is_admin=request.user.is_admin)
        if form.is_valid():
            user.email = form.cleaned_data['email']
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.phone_number = form.cleaned_data['phone_number']
            user.address = form.cleaned_data['address']
            user.subtype = form.cleaned_data['subtype']

            for queue_elem in user.requestqueueelement_set.all():
                queue_elem.priority = queue_elem.default_priority()
                queue_elem.save()

            user.groups.clear()
            if form.cleaned_data['subtype'] == 'Librarians (Priv1)':
                user.groups.add(get_or_create_group(name='Librarians (Priv1)'))
            elif form.cleaned_data['subtype'] == 'Librarians (Priv2)':
                user.groups.add(get_or_create_group(name='Librarians (Priv2)'))
            elif form.cleaned_data['subtype'] == 'Librarians (Priv3)':
                user.groups.add(get_or_create_group(name='Librarians (Priv3)'))
            elif form.cleaned_data['subtype'] == 'Students':
                user.groups.add(get_or_create_group(name='Students'))
            elif form.cleaned_data['subtype'] == 'Visiting Professors':
                user.groups.add(get_or_create_group(name='Visiting Professors'))
            else:  # if self.cleaned_data['subtype'] equal 'Instructors' or 'TAs' or 'Professors'
                user.groups.add(get_or_create_group(name='Faculty'))

            user.save()
            return HttpResponseRedirect('../')
    else:
        form = CustomUserChangeForm(instance=user, caller_is_admin=request.user.is_admin)

    return render(request, 'login/edit_user.html', {'form': form, 'permissions': user.user_permissions.all()})


def login(request):
    """
    Login view.
    :param request: HTTP request.
    :return: login.html rendered with given context.
    """
    context = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect('/')
        else:
            login_error = "User doesn't exist"
            context = {'login_error': login_error}
            return render(request, 'login.html', context)

    else:
        return render(request, 'login.html', context)


@permission_required('login.add_customuser')
def add_user(request):
    """
    View function for adding a book.
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, caller_is_admin=request.user.is_admin)
        if form.is_valid():
            user = form.save(commit=True)
            user.creator_email = request.user.email
            user.save()
            form.save(commit=True)
            return HttpResponseRedirect('../')
    else:
        form = CustomUserCreationForm(caller_is_admin=request.user.is_admin)

    return render(request, 'add_user.html', {'form': form})


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

login/templates/login/customuser_detail.html
{% extends "base_generic.html" %}
{% load login_extras %}

{% block content %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <h1> {{ customuser.first_name }} {{ customuser.last_name }}
        {% if user.is_authenticated and perms.login.change_customuser %}
            <a class="btn btn-primary" href="{% url 'edituser' customuser.id %}">Edit&nbsp;&nbsp;<i class="glyphicon glyphicon-edit"></i></a>
        {% endif %}
    </h1>

    <p><strong>E-mail:</strong> {{ customuser.email }} </p>
    <p><strong>Phone number:</strong> {{ customuser.phone_number }}</p>
    <p><strong>Address:</strong> {{ customuser.address }}</p>
    <p><strong>Type:</strong> {{ customuser.groups.first }}</p>

    <div>
        {% if user.is_authenticated and perms.login.change_customuser %}
            {% if customuser.record_set.all.count != 0 %}
                <p><a class="btn btn-danger" disabled="disabled" data-toggle="tooltip" data-placement="right" title="This user has some reserved or taken documents">Delete user</a></p>

                <div class="alert alert-info">
                    <h3>Requests:</h3>
                    {% if not customuser|reserved_books_list %}
                        <h4>This user has no requests</h4>
                    {% else %}
                        <input class="form-control" id="ReservedDocs" type="text" placeholder="Search..">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Authors</th>
                                <th>Give document</th>
                            </tr>
                            </thead>
                            <tbody id="DocumentReservedList">

                            {% for rec in customuser|reserved_books_list %}
                                <tr>
                                    <td><a href="{{ rec.document.get_absolute_url }}">{{ rec.document.title }}</a></td>
                                    <td>
                                        {{ rec.document.display_authors }}
                                    </td>
                                    <td><a class="btn btn-info" href="{% url 'give_document' rec.document.id customuser.id %}">Give document</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>

                <div class="alert alert-success">
                    <h3>Documents:</h3>

                    {% if not customuser|taken_books_list %}
                        <h4>This user has no documents</h4>
                    {% else %}

                        <input class="form-control" id="TakenDocs" type="text" placeholder="Search..">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Authors</th>
                                <th>Due to</th>
                                <th>Collect</th>
                                <th>Ask for return</th>
                                <th>Delete this copy</th>
                            </tr>
                            </thead>
                            <tbody id="DocumentTakenList">

                            {% for rec in customuser|taken_books_list %}
                                {% if customuser|overdue_document:rec.document %}
                                    <tr class="danger">
                                {% else %}
                                    <tr>
                                {% endif %}
                                    <td><a href="{{ rec.document.get_absolute_url }}">{{ rec.document.title }}</a></td>
                                    <td>
                                        {{ rec.document.display_authors }}
                                    </td>
                                    <td>{{ rec.due_to }}</td>
                                    <td><a class="btn btn-success" href="{% url 'take' rec.document.id customuser.id %}">Collect</a></td>
                                    <td><a class="btn btn-warning" href="{% url 'ask' rec.document.id customuser.id %}">Ask for return</a></td>
                                    <td><a class="btn btn-danger" href="{% url 'delete_copy' rec.document.id customuser.id %}">Delete this copy</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            {% else %}
                {% if user.id == customuser.id %}
                    <p><a class="btn btn-danger" disabled="disabled" data-toggle="tooltip" data-placement="right" title="You can not delete yourself">Delete user</a></p>
                {% else %}
                    {% if perms.login.delete_customuser %}
                    <p><a class="btn btn-danger" href="{% url 'deleteuser' customuser.id %}">Delete user</a></p>
                    {% else %}
                    <p><a class="btn btn-danger" disabled="disabled" data-toggle="tooltip" data-placement="right" title="Sorry. You have no permission for this action">Delete user</a></p>
                    {% endif %}
                {% endif %}
                <div class="alert alert-warning"><h4>This user has no any documents or requests</h4></div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

login/templates/login/customuser_list.html
{% extends "base_generic.html" %}
{% load login_extras %}

{% block content %}

    <h1>User List</h1>

    <button type="button" class="btn btn-success" data-toggle="collapse" data-target="#UsersWithBooks">Show users with books only</button>
    <br>
    <br>
    <div id="UsersWithBooks" class="collapse">
        <div class="alert alert-success">
            <h3>Users with books</h3>
            <div class="col-md-*">
            <input class="form-control" id="UserBooksSearch" type="text" placeholder="Search..">
            {% if customuser_list|users_with_books %}
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Type</th>
                        <th>Books</th>
                    </tr>
                    </thead>
                    <tbody id="UserBooksList">
                    {% for user in customuser_list|users_with_books %}
                        {% if user|is_debtor %}
                            <tr class="danger">
                        {% else %}
                            <tr>
                        {% endif %}
                        <td><a href = "{{ user.get_absolute_url }}">{{ user.email }}</a></td>
                        <td><a href = "{{ user.get_absolute_url }}">{{user.first_name}}</a></td>
                        <td><a href = "{{ user.get_absolute_url }}">{{user.last_name}}</a></td>
                        <td>
                            {{ user.subtype }}
                            {% if user.groups.all.first.name != user.subtype %}
                            ({{ user.groups.all.first }})
                            {% endif %}
                        </td>
                        <td>
                            {% for book in customuser_list|books_of_user:user %}
                                {% for info in book %}
                                    {% if forloop.last %}
                                        (due to: {{ info }})
                                    {% else %}
                                        <a href="{{ info.get_absolute_url }}">{{ info.title }}</a>
                                    {% endif %}
                                {% endfor %}
                                {% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </td>
                        {% if user|is_debtor %}
                            <td style="display:none">debtors overdue</td>
                        {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                There is no users with books in the system
            {% endif %}
        </div>

            To show all debtors search for "debtor" or "overdue"


        </div>
    </div>

    <div class="alert alert-info">
        {% if request.user.is_admin %}
            <h3> All users </h3>
        {% else %}
            <h3> All patrons </h3>
        {% endif %}
        <div class="col-md-*">
            <input class="form-control" id="UsersSearch" type="text" placeholder="Search..">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>Email</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Type</th>
                </tr>
                </thead>
                <tbody id="UserList">
                {% for user in customuser_list|patrons:request.user.is_admin %}
                    {% if user|is_debtor %}
                        <tr class="danger">
                    {% else %}
                        <tr>
                    {% endif %}
                    <td><a href = "{{ user.get_absolute_url }}">{{ user.email }}</a></td>
                    <td><a href = "{{ user.get_absolute_url }}">{{user.first_name}}</a></td>
                    <td><a href = "{{ user.get_absolute_url }}">{{user.last_name}}</a></td>
                    <td>
                        {{ user.subtype }}
                        {% if user.groups.all.first.name != user.subtype %}
                        ({{ user.groups.all.first }})
                        {% endif %}
                    </td>
                    {% if user|is_debtor %}
                        <td style="display:none">debtors overdue</td>
                    {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        To show all debtors search for "debtor" or "overdue"

    </div>

{% endblock %}

login/templates/login/edit_user.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Edit user</h1>
    <form method="POST" autocomplete="on">
    {% csrf_token %}
        {{ form | crispy }}
        <input class="btn btn-primary" type="submit" value="Submit" />
    <br>
    <br>
    </form>
{% endblock %}